In [1]:
import numpy as np
a= np.array([2,3,4])

In [2]:
a.dtype

dtype('int32')

In [5]:
a= np.array([[2,3,4],[5,6,7]])
print(a)

[[2 3 4]
 [5 6 7]]


# complex
Los números complejos son aquellos que tienen parte imaginaria. Si no conocías de su existencia, es más que probable que nunca lo vayas a necesitar.

De hecho la mayor parte de lenguajes de programación carecen de este tipo, aunque sea muy utilizado por ingenieros y científicos en general.

En el caso de que necesite utilizar números complejos, o simplemente tiene curiosidad, este tipo, llamado complex en Python, también se almacena usando coma flotante, debido a que estos números son una extensión de los números reales.

En concreto se almacena en una estructura de C, compuesta por dos variables de tipo double, sirviendo una de ellas para almacenar la parte real y la otra para la parte imaginaria.

Los números complejos en Python se representan de la siguiente forma:

complejo = 2.1 + 7.8j

In [6]:
c= np.array([[2,3],[5,6]], dtype= complex)
c

array([[2.+0.j, 3.+0.j],
       [5.+0.j, 6.+0.j]])

In [8]:
# genera una secuencia de números.
# Toma como parámetros el rango de los números a generar, y la distancia entre ellos, y genera un array unidimensional
# numpy.arange([start,] stop, [step,]dtype=None)
a= np.arange(1,10,2)
a


array([1, 3, 5, 7, 9])

In [10]:
# Se puede redimensionar el array que genera arange() mediante el método reshape(), que toma como argumentos la dimensiones. 
# Las dimensiones deben ser consistentes con el número de elementos generados
# array([[2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8],
#      [4.1, 4.4, 4.7, 5. , 5.3, 5.6, 5.9]])

b= np.arange(2,6,0.3).reshape(2,7) # 2 arrays de 7 elementos
b

array([[2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8],
       [4.1, 4.4, 4.7, 5. , 5.3, 5.6, 5.9]])

In [13]:
# Cuando se usan argumentos reales con arange(),
# es mejor usar la función linspace, que también genera una secuencia de números a partir de
# un rango dado para crear un array, pero recibe como tercer argumento el número de elementos,
# en vez de la distancia entre ellos.

a= np.linspace(1,10,8)
a

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [14]:
# Creación de un array unidimensional con datos aleatorios mediante la función rand del módulo Random.
# La función rand devuelve un número aleatorio procedente de una distribución uniforme en el intervalo [0,1].

a= np.random.rand(10)
a


array([0.72868145, 0.96255071, 0.68814127, 0.50852158, 0.88520357,
       0.08681024, 0.81009389, 0.83667172, 0.44165717, 0.90154764])

In [15]:
b= np.random.rand(3,4) # valores aleatoros - 3 filas, 4 columnas
b

array([[0.02142838, 0.66577739, 0.4982237 , 0.58589554],
       [0.0520409 , 0.2267725 , 0.45569262, 0.50842992],
       [0.41651661, 0.14457622, 0.05634743, 0.62725057]])

In [20]:
# Existen funciones que generan arrays especiales que solo requieren como argumento el tamaño del array
a= np.zeros(4)
print("zeros: ",a)
b= np.ones([1,2])
print("ones: ", b)
c= np.empty((2,3))
print("empty: ",c)

zeros:  [0. 0. 0. 0.]
ones:  [[1. 1.]]
empty:  [[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
# Operaciones sobre la misma posición
a= np.array([34,12,3,4])
b= np.array([2,3,5,6])
c= a-b
print("Resta:", c)
d= a*10
print("Multiplicar elementos por 10:", d)

Resta: [32  9 -2 -2]
Multiplicar elementos por 10: [340 120  30  40]


# Arrays de diferente tipo
  Cuando se opera con arrays de diferente tipo, el tipo del array resultante corresponde al más genera

In [24]:
a= np.array([2,3,6,7])
b= np.linspace(2,3,4)
c= a+b
c.dtype

dtype('float64')

# Funciones matemáticas universales
En NumPy existe un conjunto de funciones matemáticas denominadas funciones universales: sin, cos ,exp… . Estas funciones operan elemento a elemento y generan como resultado un nuevo array.

In [27]:
a= np.array([-7,60,-9])
b= np.square(a)
b

array([  49, 3600,   81], dtype=int32)

In [28]:
c= np.sqrt(np.abs(a))
c

array([2.64575131, 7.74596669, 3.        ])

In [30]:
#En particular es muy útil la función dot(), que permite realizar la multiplicación matricial
a= np.array([[2,3],[4,5]])
b= np.array([[1,2],[0,1]])
c= np.dot(a,b)
c

array([[ 2,  7],
       [ 4, 13]])

In [31]:
a= np.array([2,3])
b= np.array([1,2])
c= np.dot(a,b)
c

8

In [ ]:
# El argumento axis
# Existen algunas operaciones implementadas como métodos de la clase ndarray y, por defecto, 
# se aplican a todos los elementos del array. Sin embargo, es posible especificar la dimensión 
# sobre la que se quiere aplicar la operación mediante el argumento axis 
# que toma el valor 0 (columnas) o 1 (filas)

b= np.empty((3,4))
b


In [41]:
b.sum()

4.258951784837528

In [42]:
b.sum(axis=0)

array([0.48998589, 1.03712611, 1.01026375, 1.72157603])

# Operadores += y *=
 Los operadores += y *= modifican los arrays en vez de crear uno nuevo 

In [45]:
a= np.array([2,3,5,6])
a+=3
a

array([5, 6, 8, 9])

In [46]:
a*=a
a

array([25, 36, 64, 81])